name: Linting

on:
  push:

  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9
        architecture: x64

    - name: Install Poetry and Nox
      run: pip install poetry nox

    - name: Run Linting
      env:
        NOXSESSION: lint
      run: nox
