name: Linting

on:
  push:

  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    env:
      PRE_COMMIT_HOME: ${{ github.workspace }}/.cache/pre-commit-cache

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9
        architecture: x64

    - name: Cache Pip Folder
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'poetry.lock') }}

    - name: Install Poetry and Nox
      run: pip install poetry nox

    - name: Cache Nox Environments
      uses: actions/cache@v2
      with:
        path: .nox
        key: nox-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'poetry.lock') }}

    - name: Cache Pre-Commit Environments
      uses: actions/cache@v2
      with:
        path: ${{ env.PRE_COMMIT_HOME }}
        key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Run Linting
      env:
        NOXSESSION: lint
      run: nox -r
