name: Linting

on:
  push:

  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9
        architecture: x64

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.1.0

    - name: Install Dependencies
      run: |
        poetry install
        poetry run pre-commit install

    - name: Run Linting
      run: poetry run pre-commit run --all-files
